name: Release

on:
  push:
    branches:    
      - 'releases/**'
    tags:        
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: actions/checkout@v2
      with:
        ref: 'master'
        fetch-depth: 0

    - name: Checkout to tag
      run: git checkout ${{ github.ref }}

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Build
      run: | 
        npm install
        sh ./release.sh
      env: 
        YANDEX_AUTH_TOKEN: ${{ secrets.YANDEX_AUTH_TOKEN }}
        YANDEX_ORG_ID: ${{ secrets.YANDEX_ORG_ID }}    
        GITHUB_SERVER_URL: ${{ github.GITHUB_SERVER_URL }}
        GITHUB_REPOSITORY: ${{ github.GITHUB_REPOSITORY }}
        GITHUB_ACTION: ${{ github.GITHUB_ACTION }}
