name: Release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Build
      run: |
        npm install
        ./release.sh
      env: 
        YANDEX_AUTH_TOKEN: ${{ secrets.YANDEX_AUTH_TOKEN }}
        YANDEX_ORG_ID: ${{ secrets.YANDEX_ORG_ID }}
